### ISSUE TITLE
Minor: Figures 3.1, 3.2 don't quite match XML

### ISSUE THREAD

**Issue by jem6** [grantm/perl-libxml-by-example#1]
In both figures, the `<book>` element has an `edition="2"` attribute, but `book.xml` at the beginning of the chapter has the attribute on the `<title>` element.

Great tutorial BTW.

**Comment by grantm** [comment]
Thanks for the catch.  Not sure why I put it on the `<title>` element in the XML file, but I've updated it now to match the pictures.  I didn't end up referring to it from the text anyway.

Thanks again.
